apiVersion: v1
kind: Service
metadata:
  name: my-nodejs
  labels:
    app: nodejs
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8089
    targetPort: 8089
#  - name: harshad
#    port: 8081
#    targetPort: 8081
#  - name: bharath
#    port: 8083
#    targetPort: 8083
  selector:
    app: nodejs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs

    spec:
      containers:
        - name: nodejs
          image: harshad/nojejs-k8s
          resources:
            limits:
              memory:  "128Mi"
              cpu: "250m"
            requests:
              memory: "100Mi"
              cpu: "250m"

          ports:
          - name: port8089
            containerPort: 8089
